### ISSUE TITLE
dynamicItemOpacity not working

### ISSUE THREAD

**Issue by ghprod** [MSVCode/scroll_snap_list#10]
Hi

I'm using your [vertical example](https://github.com/MSVCode/scroll_snap_list/blob/master/example/vertical_list.dart) with an additional `dynamicItemOpacity` parameter, but not working

```dart
ScrollSnapList(
    onItemFocus: _onItemFocus,
    itemSize: 50,
    dynamicItemOpacity: 0.3, // here the opacity
    itemBuilder: _buildListItem,
    itemCount: data.length,
    key: sslKey,
    scrollDirection: Axis.vertical,
  ),
),
```

And this is the screenshot

![image](https://user-images.githubusercontent.com/1922652/103414642-54dd0e80-4bb1-11eb-97df-acc2b3109714.png)

Seems like the 1.0 opacity stuck on Index 0, no matter which one you selected

```
$ flutter doctor -v
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.22.4 at /home/bolt/dev/data/flutter
    • Framework revision 1aafb3a8b9 (7 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
```

Thanks

**Comment by MSVCode** [comment]
Thanks @ghprod for the issue report.

It's fixed in `v0.6.0`.

For older version we need to set `dynamicItemSize:true` in order to work.
