### ISSUE TITLE
Add ListView clipBehavior option

### ISSUE THREAD

**Issue by umaqs** [MSVCode/scroll_snap_list#13]
`ListView` `clipBehavior` defaults to `Clip.hardEdge` which blocks any bleeding decoration (shadows/border) applied to the items.

It would be beneficial to add the `clipBehavior` option in the constructor to enable the ability to customise the list items.

**Comment by MSVCode** [comment]
Thank you for the input. Several new `ListView` parameters added in version `0.8.0`.
