### ISSUE TITLE
On iOS with START - Anchor, list hangs itself on the last item

### ISSUE THREAD

**Issue by JamesCullum** [MSVCode/scroll_snap_list#17]
You can see the issue in the video below - if the list is scrolled to the end on iOS (on Android it doesn't, but this may be due to the screen resolution differences) and the width is not wide enough to fill the whole width, the list will continuously try and fail to scroll to the latest item, creating a jiggling motion. Please be aware that after pulling to the right side in the demo video, it is not touched manually anymore.

https://user-images.githubusercontent.com/5477111/125519502-84c82e43-65d0-4de4-b95c-a788c7df12d9.mov

This is the code that creates the list - it uses dynamic width and height to make sure it fits for all screens.

```dart
Container(
	height: calcCardHeight.containsKey(index) &&
			calcCardHeight[index].keys.length == 2
		? calcCardHeight[index][0] +
			calcCardHeight[index][1] +
			5.0
		: 250,
	child: ScrollSnapList(
	  listViewKey: ObjectKey(index),
	  itemBuilder: (BuildContext context, int index) =>
		  travelStepRow[index],
	  itemCount: travelStepRow.length,
	  itemSize: cardWidth,
	  selectedItemAnchor: SelectedItemAnchor.START,
	  dynamicItemSize: true,
	  dynamicSizeEquation: (double distance) =>
		  1.0 - (distance / 2000).abs(),
	  onItemFocus: (int index) {},
	  listController: controller,
	)
),
```

**Comment by vaetas** [comment]
I have problem with this too. I believe that the last item should have `SelectedItemAnchor.END` even when you set default as `START` so it looks and behaves nicely.

To quickly remove the scroll jumping, I've added a transparent `SizedBox` widget with remaining width to the end of items. This fills the end of viewport and stops the scrolling. However, the last item is then aligned to the left side and the user cannot see any part of previous items. Therefore it might look like an list view single item.

**Comment by vaetas** [comment]
Slightly better temporary fix: replace this line in [https://github.com/MSVCode/scroll_snap_list/blob/master/lib/scroll_snap_list.dart#L365](https://github.com/MSVCode/scroll_snap_list/blob/master/lib/scroll_snap_list.dart#L365) with following code.

```dart
_animateScroll(
  min(offset, scrollInfo.metrics.maxScrollExtent),
);
```

This will prevent scroll controller from scrolling beyond the scroll end. This also seems why you can only see this behavior on iOS as it allows the over-scroll bounce physics. Android ignores attempts to scroll over the end.

**Comment by JamesCullum** [comment]
That sounds like it would be a good small fix for a PR - do you want to create it?

**Comment by vaetas** [comment]
I could make a PR if @MSVCode agrees to my solution.

**Comment by MSVCode** [comment]
Thank you @JamesCullum for the issue report and @vaetas for the possible fix. 

It seems the problem comes from `cardIndex` calculation (the over-scroll in iOS resulting out-of-bounds index). So i tried to add extra check in `_calcCardLocation`.

This fix is published in version `0.8.2`.

Unfortunately i don't have the environment to test iOS-related bug, so i need help to confirm whether it's fixed or not.

**Comment by JamesCullum** [comment]
Thanks a lot for the help @MSVCode - will update it and let you know the result!

**Comment by MSVCode** [comment]
Considered fixed
