### ISSUE TITLE
Remove ! from widgetbinding instance

### ISSUE THREAD

**Issue by rienkkk** [MSVCode/scroll_snap_list#29]
In flutter 3.0, WidgetBinding.instance is not nullable. So the null aware operator! can be removed.
Currently, when using flutter 3.0, this package gives the following error:

> Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
> ../…/lib/scroll_snap_list.dart:177
> - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/C:/src/flutter/packages/flutter/lib/src/widgets/binding.dart').
> package:flutter/…/widgets/binding.dart:1
>     WidgetsBinding.instance!.addPostFrameCallback((_)

Change InitState to:

```
void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (widget.initialIndex != null) {
        //set list's initial position
        focusToInitialPosition();
      } else {
        isInit = false;
      }
    });

    ///After initial jump, set isInit to false
    Future.delayed(Duration(milliseconds: 10), () {
      if (this.mounted) {
        setState(() {
          isInit = false;
        });
      }
    });
  }
```

**Comment by MSVCode** [comment]
Fixed in `0.9.1`
