### ISSUE TITLE
Determining anchor

### ISSUE THREAD

**Issue by EimantasGag** [MSVCode/scroll_snap_list#31]
**Hey, thanks for your awesome library**, though I am facing an issue, because I want to determine anchor myself and cases like `SelectedItemAnchor.START`, `SelectedItemAnchor.MIDDLE`, `SelectedItemAnchor.END` don't work for me. 

I am suggesting, that you create another function `determineAnchor()` and put the whole `switch()` statement, that calculates `_listPadding` in there. Then I will be able to simply extend the class and override the `determineAnchor()`.

**Comment by MSVCode** [comment]
Thanks for the suggestion.

`_listPadding` calculation now calls `calculateListPadding` in `0.9.1`
