### ISSUE TITLE
Feature Request: Include PageStorageKey

### ISSUE THREAD

**Issue by TinNova** [MSVCode/scroll_snap_list#5]
Hi, the package is great! Thanks for creating it.

I noticed that the ScrollSnapList can only accept one key, which means if I want to save the index of the last focused item after a rebuild I need to use PageStorageKey.

Therefore I lose the ability to use your ScrollSnapListState.

It would be great if both keys could be used.

**Comment by MSVCode** [comment]
Hi @TinNova, thank you for using this package and your suggestion.

I've added `listViewKey` that passes the key to child `ListView` used by `ScrollSnapList` in version `0.4.1` . So now you can pass `PageStorageKey` there to preserve scroll location.

I also added the demo for it: https://github.com/MSVCode/scroll_snap_list/blob/master/example/tab_with_horizontal.dart
