### ISSUE TITLE
Snap to left / right of screen instead of center

### ISSUE THREAD

**Issue by reesz** [MSVCode/scroll_snap_list#7]
Hello,

I was really glad when I found your package, since this really does the trick for my use case (free scrolling + snap at the end).
The only thing I was wondering: Since I have a left aligned layout and not a centered one, is there a way to snap to the left side of the container instead of centering the focused item?

Thanks & have a nice day.

Flo,

**Comment by MSVCode** [comment]
Custom anchor position now available in `v0.6.0`

To use it add parameter `selectedItemAnchor: SelectedItemAnchor.START` or `SelectedItemAnchor.END` in `ScrollSnapList`
