### ISSUE TITLE
Listcontroller

### ISSUE THREAD

**Issue by zaimanza** [MSVCode/scroll_snap_list#9]
I am trying to use listController so that I can animate to the user's selected index. But when I use 

int index = 3;

controller.animateTo( 
  index, 
  duration: Duration(milliseconds: 1000),
  curve: Curves.ease,
) 

It will scroll back to index 0

**Comment by MSVCode** [comment]
Hi @zaimanza, Flutter's `ScrollController` is pixel-based not index-based. Which means in your code, you scroll with 3 pixel offset (so it looks like index 0).

If you wanted to scroll to index programmatically you can use state's `focusToItem`, don't create your own controller.

The examples already discuss about this: https://github.com/MSVCode/scroll_snap_list/blob/master/example/vertical_list.dart
